// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vivserver.proto

#include "vivserver.pb.h"
#include "vivserver.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Emulator_method_names[] = {
  "/Emulator/RunNumInstructions",
};

std::unique_ptr< Emulator::Stub> Emulator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Emulator::Stub> stub(new Emulator::Stub(channel, options));
  return stub;
}

Emulator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RunNumInstructions_(Emulator_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Emulator::Stub::RunNumInstructions(::grpc::ClientContext* context, const ::RunInstructionsRequest& request, ::RunInstructionsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RunInstructionsRequest, ::RunInstructionsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RunNumInstructions_, context, request, response);
}

void Emulator::Stub::async::RunNumInstructions(::grpc::ClientContext* context, const ::RunInstructionsRequest* request, ::RunInstructionsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RunInstructionsRequest, ::RunInstructionsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunNumInstructions_, context, request, response, std::move(f));
}

void Emulator::Stub::async::RunNumInstructions(::grpc::ClientContext* context, const ::RunInstructionsRequest* request, ::RunInstructionsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunNumInstructions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RunInstructionsReply>* Emulator::Stub::PrepareAsyncRunNumInstructionsRaw(::grpc::ClientContext* context, const ::RunInstructionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RunInstructionsReply, ::RunInstructionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RunNumInstructions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RunInstructionsReply>* Emulator::Stub::AsyncRunNumInstructionsRaw(::grpc::ClientContext* context, const ::RunInstructionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRunNumInstructionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Emulator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Emulator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Emulator::Service, ::RunInstructionsRequest, ::RunInstructionsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Emulator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RunInstructionsRequest* req,
             ::RunInstructionsReply* resp) {
               return service->RunNumInstructions(ctx, req, resp);
             }, this)));
}

Emulator::Service::~Service() {
}

::grpc::Status Emulator::Service::RunNumInstructions(::grpc::ServerContext* context, const ::RunInstructionsRequest* request, ::RunInstructionsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


