#!/usr/bin/env bash

set -e

DOCKER_SSH_PORT=$((DOCKER_UID + 1222))
export DOCKER_SSH_PORT
DOCKER_HOSTNAME="$(hostname)-mcad"
export DOCKER_HOSTNAME
DOCKER_USER=$(id -un)
export DOCKER_USER

# [2024/04/17:JCC] We want a constant docker name for use in the PATE Binja Plugin
# [2024/04/17:JCC] Don't want up, just build the container
# [2024/04/18:JCC] If having cache issus add --pull --no-cache
docker-compose --project-name "mcad" build
