// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: emulator.proto

#include "emulator.pb.h"
#include "emulator.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* Emulator_method_names[] = {
  "/Emulator/RecordEmulatorActions",
};

std::unique_ptr< Emulator::Stub> Emulator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Emulator::Stub> stub(new Emulator::Stub(channel));
  return stub;
}

Emulator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RecordEmulatorActions_(Emulator_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Emulator::Stub::RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::NextAction* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RecordEmulatorActions_, context, request, response);
}

void Emulator::Stub::experimental_async::RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RecordEmulatorActions_, context, request, response, std::move(f));
}

void Emulator::Stub::experimental_async::RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RecordEmulatorActions_, context, request, response, std::move(f));
}

void Emulator::Stub::experimental_async::RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RecordEmulatorActions_, context, request, response, reactor);
}

void Emulator::Stub::experimental_async::RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RecordEmulatorActions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NextAction>* Emulator::Stub::AsyncRecordEmulatorActionsRaw(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::NextAction>::Create(channel_.get(), cq, rpcmethod_RecordEmulatorActions_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::NextAction>* Emulator::Stub::PrepareAsyncRecordEmulatorActionsRaw(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::NextAction>::Create(channel_.get(), cq, rpcmethod_RecordEmulatorActions_, context, request, false);
}

Emulator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Emulator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Emulator::Service, ::EmulatorActions, ::NextAction>(
          [](Emulator::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::EmulatorActions* req,
             ::NextAction* resp) {
               return service->RecordEmulatorActions(ctx, req, resp);
             }, this)));
}

Emulator::Service::~Service() {
}

::grpc::Status Emulator::Service::RecordEmulatorActions(::grpc::ServerContext* context, const ::EmulatorActions* request, ::NextAction* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


