# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emulator_pb2 as emulator__pb2


class EmulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordEmulatorActions = channel.unary_unary(
                '/Emulator/RecordEmulatorActions',
                request_serializer=emulator__pb2.EmulatorActions.SerializeToString,
                response_deserializer=emulator__pb2.NextAction.FromString,
                )


class EmulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordEmulatorActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordEmulatorActions': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEmulatorActions,
                    request_deserializer=emulator__pb2.EmulatorActions.FromString,
                    response_serializer=emulator__pb2.NextAction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Emulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Emulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordEmulatorActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Emulator/RecordEmulatorActions',
            emulator__pb2.EmulatorActions.SerializeToString,
            emulator__pb2.NextAction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
