// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: emulator.proto
#ifndef GRPC_emulator_2eproto__INCLUDED
#define GRPC_emulator_2eproto__INCLUDED

#include "emulator.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class Emulator final {
 public:
  static constexpr char const* service_full_name() {
    return "Emulator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::NextAction* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NextAction>> AsyncRecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NextAction>>(AsyncRecordEmulatorActionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NextAction>> PrepareAsyncRecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NextAction>>(PrepareAsyncRecordEmulatorActionsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NextAction>* AsyncRecordEmulatorActionsRaw(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NextAction>* PrepareAsyncRecordEmulatorActionsRaw(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::NextAction* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NextAction>> AsyncRecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NextAction>>(AsyncRecordEmulatorActionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NextAction>> PrepareAsyncRecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NextAction>>(PrepareAsyncRecordEmulatorActionsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, std::function<void(::grpc::Status)>) override;
      void RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RecordEmulatorActions(::grpc::ClientContext* context, const ::EmulatorActions* request, ::NextAction* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RecordEmulatorActions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NextAction* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NextAction>* AsyncRecordEmulatorActionsRaw(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NextAction>* PrepareAsyncRecordEmulatorActionsRaw(::grpc::ClientContext* context, const ::EmulatorActions& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RecordEmulatorActions_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* context, const ::EmulatorActions* request, ::NextAction* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RecordEmulatorActions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecordEmulatorActions() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RecordEmulatorActions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecordEmulatorActions(::grpc::ServerContext* context, ::EmulatorActions* request, ::grpc::ServerAsyncResponseWriter< ::NextAction>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RecordEmulatorActions<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RecordEmulatorActions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RecordEmulatorActions() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::EmulatorActions, ::NextAction>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::EmulatorActions* request, ::NextAction* response) { return this->RecordEmulatorActions(context, request, response); }));}
    void SetMessageAllocatorFor_RecordEmulatorActions(
        ::grpc::experimental::MessageAllocator< ::EmulatorActions, ::NextAction>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::EmulatorActions, ::NextAction>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RecordEmulatorActions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RecordEmulatorActions(
      ::grpc::CallbackServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RecordEmulatorActions(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RecordEmulatorActions<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RecordEmulatorActions<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RecordEmulatorActions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecordEmulatorActions() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RecordEmulatorActions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecordEmulatorActions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecordEmulatorActions() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RecordEmulatorActions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecordEmulatorActions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RecordEmulatorActions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RecordEmulatorActions() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecordEmulatorActions(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RecordEmulatorActions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RecordEmulatorActions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RecordEmulatorActions(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecordEmulatorActions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecordEmulatorActions() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::EmulatorActions, ::NextAction>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::EmulatorActions, ::NextAction>* streamer) {
                       return this->StreamedRecordEmulatorActions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecordEmulatorActions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecordEmulatorActions(::grpc::ServerContext* /*context*/, const ::EmulatorActions* /*request*/, ::NextAction* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecordEmulatorActions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::EmulatorActions,::NextAction>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RecordEmulatorActions<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RecordEmulatorActions<Service > StreamedService;
};


#endif  // GRPC_emulator_2eproto__INCLUDED
