// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: binja.proto

#include "binja.pb.h"
#include "binja.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Binja_method_names[] = {
  "/Binja/RequestCycleCounts",
};

std::unique_ptr< Binja::Stub> Binja::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Binja::Stub> stub(new Binja::Stub(channel, options));
  return stub;
}

Binja::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestCycleCounts_(Binja_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Binja::Stub::RequestCycleCounts(::grpc::ClientContext* context, const ::BinjaInstructions& request, ::CycleCounts* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BinjaInstructions, ::CycleCounts, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestCycleCounts_, context, request, response);
}

void Binja::Stub::async::RequestCycleCounts(::grpc::ClientContext* context, const ::BinjaInstructions* request, ::CycleCounts* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BinjaInstructions, ::CycleCounts, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestCycleCounts_, context, request, response, std::move(f));
}

void Binja::Stub::async::RequestCycleCounts(::grpc::ClientContext* context, const ::BinjaInstructions* request, ::CycleCounts* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestCycleCounts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::CycleCounts>* Binja::Stub::PrepareAsyncRequestCycleCountsRaw(::grpc::ClientContext* context, const ::BinjaInstructions& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::CycleCounts, ::BinjaInstructions, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestCycleCounts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::CycleCounts>* Binja::Stub::AsyncRequestCycleCountsRaw(::grpc::ClientContext* context, const ::BinjaInstructions& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestCycleCountsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Binja::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Binja_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Binja::Service, ::BinjaInstructions, ::CycleCounts, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Binja::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BinjaInstructions* req,
             ::CycleCounts* resp) {
               return service->RequestCycleCounts(ctx, req, resp);
             }, this)));
}

Binja::Service::~Service() {
}

::grpc::Status Binja::Service::RequestCycleCounts(::grpc::ServerContext* context, const ::BinjaInstructions* request, ::CycleCounts* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


