// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binja.proto

#include "binja.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CycleCounts_CycleCount::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : start_{::uint64_t{0u}},
        end_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CycleCounts_CycleCount::CycleCounts_CycleCount(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CycleCounts_CycleCountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CycleCounts_CycleCountDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CycleCounts_CycleCountDefaultTypeInternal() {}
  union {
    CycleCounts_CycleCount _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CycleCounts_CycleCountDefaultTypeInternal _CycleCounts_CycleCount_default_instance_;

inline constexpr BinjaInstructions_Instruction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : opcode_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BinjaInstructions_Instruction::BinjaInstructions_Instruction(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BinjaInstructions_InstructionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BinjaInstructions_InstructionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BinjaInstructions_InstructionDefaultTypeInternal() {}
  union {
    BinjaInstructions_Instruction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BinjaInstructions_InstructionDefaultTypeInternal _BinjaInstructions_Instruction_default_instance_;

inline constexpr CycleCounts::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cycle_counts_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CycleCounts::CycleCounts(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CycleCountsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CycleCountsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CycleCountsDefaultTypeInternal() {}
  union {
    CycleCounts _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CycleCountsDefaultTypeInternal _CycleCounts_default_instance_;

inline constexpr BinjaInstructions::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : instructions_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BinjaInstructions::BinjaInstructions(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BinjaInstructionsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BinjaInstructionsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BinjaInstructionsDefaultTypeInternal() {}
  union {
    BinjaInstructions _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BinjaInstructionsDefaultTypeInternal _BinjaInstructions_default_instance_;
static ::_pb::Metadata file_level_metadata_binja_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_binja_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_binja_2eproto = nullptr;
const ::uint32_t TableStruct_binja_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::BinjaInstructions_Instruction, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BinjaInstructions_Instruction, _impl_.opcode_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::BinjaInstructions, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BinjaInstructions, _impl_.instructions_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CycleCounts_CycleCount, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CycleCounts_CycleCount, _impl_.start_),
    PROTOBUF_FIELD_OFFSET(::CycleCounts_CycleCount, _impl_.end_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CycleCounts, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CycleCounts, _impl_.cycle_counts_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::BinjaInstructions_Instruction)},
        {9, -1, -1, sizeof(::BinjaInstructions)},
        {18, -1, -1, sizeof(::CycleCounts_CycleCount)},
        {28, -1, -1, sizeof(::CycleCounts)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_BinjaInstructions_Instruction_default_instance_._instance,
    &::_BinjaInstructions_default_instance_._instance,
    &::_CycleCounts_CycleCount_default_instance_._instance,
    &::_CycleCounts_default_instance_._instance,
};
const char descriptor_table_protodef_binja_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013binja.proto\"h\n\021BinjaInstructions\0224\n\014in"
    "structions\030\001 \003(\0132\036.BinjaInstructions.Ins"
    "truction\032\035\n\013Instruction\022\016\n\006opcode\030\001 \001(\014\""
    "f\n\013CycleCounts\022-\n\014cycle_counts\030\001 \003(\0132\027.C"
    "ycleCounts.CycleCount\032(\n\nCycleCount\022\r\n\005s"
    "tart\030\002 \001(\004\022\013\n\003end\030\003 \001(\0042\?\n\005Binja\0226\n\022Requ"
    "estCycleCounts\022\022.BinjaInstructions\032\014.Cyc"
    "leCountsb\006proto3"
};
static ::absl::once_flag descriptor_table_binja_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_binja_2eproto = {
    false,
    false,
    296,
    descriptor_table_protodef_binja_2eproto,
    "binja.proto",
    &descriptor_table_binja_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_binja_2eproto::offsets,
    file_level_metadata_binja_2eproto,
    file_level_enum_descriptors_binja_2eproto,
    file_level_service_descriptors_binja_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_binja_2eproto_getter() {
  return &descriptor_table_binja_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_binja_2eproto(&descriptor_table_binja_2eproto);
// ===================================================================

class BinjaInstructions_Instruction::_Internal {
 public:
};

BinjaInstructions_Instruction::BinjaInstructions_Instruction(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BinjaInstructions.Instruction)
}
inline PROTOBUF_NDEBUG_INLINE BinjaInstructions_Instruction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : opcode_(arena, from.opcode_),
        _cached_size_{0} {}

BinjaInstructions_Instruction::BinjaInstructions_Instruction(
    ::google::protobuf::Arena* arena,
    const BinjaInstructions_Instruction& from)
    : ::google::protobuf::Message(arena) {
  BinjaInstructions_Instruction* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:BinjaInstructions.Instruction)
}
inline PROTOBUF_NDEBUG_INLINE BinjaInstructions_Instruction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : opcode_(arena),
        _cached_size_{0} {}

inline void BinjaInstructions_Instruction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BinjaInstructions_Instruction::~BinjaInstructions_Instruction() {
  // @@protoc_insertion_point(destructor:BinjaInstructions.Instruction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BinjaInstructions_Instruction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.opcode_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BinjaInstructions_Instruction::Clear() {
// @@protoc_insertion_point(message_clear_start:BinjaInstructions.Instruction)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.opcode_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BinjaInstructions_Instruction::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> BinjaInstructions_Instruction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_BinjaInstructions_Instruction_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes opcode = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BinjaInstructions_Instruction, _impl_.opcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes opcode = 1;
    {PROTOBUF_FIELD_OFFSET(BinjaInstructions_Instruction, _impl_.opcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* BinjaInstructions_Instruction::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BinjaInstructions.Instruction)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes opcode = 1;
  if (!this->_internal_opcode().empty()) {
    const std::string& _s = this->_internal_opcode();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BinjaInstructions.Instruction)
  return target;
}

::size_t BinjaInstructions_Instruction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BinjaInstructions.Instruction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes opcode = 1;
  if (!this->_internal_opcode().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_opcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BinjaInstructions_Instruction::_class_data_ = {
    BinjaInstructions_Instruction::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BinjaInstructions_Instruction::GetClassData() const {
  return &_class_data_;
}

void BinjaInstructions_Instruction::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BinjaInstructions_Instruction*>(&to_msg);
  auto& from = static_cast<const BinjaInstructions_Instruction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BinjaInstructions.Instruction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_opcode().empty()) {
    _this->_internal_set_opcode(from._internal_opcode());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BinjaInstructions_Instruction::CopyFrom(const BinjaInstructions_Instruction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BinjaInstructions.Instruction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BinjaInstructions_Instruction::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BinjaInstructions_Instruction::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BinjaInstructions_Instruction::InternalSwap(BinjaInstructions_Instruction* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.opcode_, &other->_impl_.opcode_, arena);
}

::google::protobuf::Metadata BinjaInstructions_Instruction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_binja_2eproto_getter, &descriptor_table_binja_2eproto_once,
      file_level_metadata_binja_2eproto[0]);
}
// ===================================================================

class BinjaInstructions::_Internal {
 public:
};

BinjaInstructions::BinjaInstructions(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BinjaInstructions)
}
inline PROTOBUF_NDEBUG_INLINE BinjaInstructions::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : instructions_{visibility, arena, from.instructions_},
        _cached_size_{0} {}

BinjaInstructions::BinjaInstructions(
    ::google::protobuf::Arena* arena,
    const BinjaInstructions& from)
    : ::google::protobuf::Message(arena) {
  BinjaInstructions* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:BinjaInstructions)
}
inline PROTOBUF_NDEBUG_INLINE BinjaInstructions::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : instructions_{visibility, arena},
        _cached_size_{0} {}

inline void BinjaInstructions::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BinjaInstructions::~BinjaInstructions() {
  // @@protoc_insertion_point(destructor:BinjaInstructions)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BinjaInstructions::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BinjaInstructions::Clear() {
// @@protoc_insertion_point(message_clear_start:BinjaInstructions)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instructions_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BinjaInstructions::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> BinjaInstructions::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_BinjaInstructions_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .BinjaInstructions.Instruction instructions = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BinjaInstructions, _impl_.instructions_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .BinjaInstructions.Instruction instructions = 1;
    {PROTOBUF_FIELD_OFFSET(BinjaInstructions, _impl_.instructions_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::BinjaInstructions_Instruction>()},
  }}, {{
  }},
};

::uint8_t* BinjaInstructions::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BinjaInstructions)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .BinjaInstructions.Instruction instructions = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_instructions_size()); i < n; i++) {
    const auto& repfield = this->_internal_instructions().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BinjaInstructions)
  return target;
}

::size_t BinjaInstructions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BinjaInstructions)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BinjaInstructions.Instruction instructions = 1;
  total_size += 1UL * this->_internal_instructions_size();
  for (const auto& msg : this->_internal_instructions()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BinjaInstructions::_class_data_ = {
    BinjaInstructions::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BinjaInstructions::GetClassData() const {
  return &_class_data_;
}

void BinjaInstructions::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BinjaInstructions*>(&to_msg);
  auto& from = static_cast<const BinjaInstructions&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BinjaInstructions)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_instructions()->MergeFrom(
      from._internal_instructions());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BinjaInstructions::CopyFrom(const BinjaInstructions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BinjaInstructions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BinjaInstructions::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BinjaInstructions::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BinjaInstructions::InternalSwap(BinjaInstructions* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.instructions_.InternalSwap(&other->_impl_.instructions_);
}

::google::protobuf::Metadata BinjaInstructions::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_binja_2eproto_getter, &descriptor_table_binja_2eproto_once,
      file_level_metadata_binja_2eproto[1]);
}
// ===================================================================

class CycleCounts_CycleCount::_Internal {
 public:
};

CycleCounts_CycleCount::CycleCounts_CycleCount(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CycleCounts.CycleCount)
}
CycleCounts_CycleCount::CycleCounts_CycleCount(
    ::google::protobuf::Arena* arena, const CycleCounts_CycleCount& from)
    : CycleCounts_CycleCount(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CycleCounts_CycleCount::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CycleCounts_CycleCount::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_),
           0,
           offsetof(Impl_, end_) -
               offsetof(Impl_, start_) +
               sizeof(Impl_::end_));
}
CycleCounts_CycleCount::~CycleCounts_CycleCount() {
  // @@protoc_insertion_point(destructor:CycleCounts.CycleCount)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CycleCounts_CycleCount::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CycleCounts_CycleCount::Clear() {
// @@protoc_insertion_point(message_clear_start:CycleCounts.CycleCount)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.start_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.end_) -
      reinterpret_cast<char*>(&_impl_.start_)) + sizeof(_impl_.end_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CycleCounts_CycleCount::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> CycleCounts_CycleCount::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967289,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CycleCounts_CycleCount_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // uint64 start = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CycleCounts_CycleCount, _impl_.start_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CycleCounts_CycleCount, _impl_.start_)}},
    // uint64 end = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CycleCounts_CycleCount, _impl_.end_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(CycleCounts_CycleCount, _impl_.end_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 start = 2;
    {PROTOBUF_FIELD_OFFSET(CycleCounts_CycleCount, _impl_.start_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 end = 3;
    {PROTOBUF_FIELD_OFFSET(CycleCounts_CycleCount, _impl_.end_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CycleCounts_CycleCount::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CycleCounts.CycleCount)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 start = 2;
  if (this->_internal_start() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_start(), target);
  }

  // uint64 end = 3;
  if (this->_internal_end() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_end(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CycleCounts.CycleCount)
  return target;
}

::size_t CycleCounts_CycleCount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CycleCounts.CycleCount)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 start = 2;
  if (this->_internal_start() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_start());
  }

  // uint64 end = 3;
  if (this->_internal_end() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_end());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CycleCounts_CycleCount::_class_data_ = {
    CycleCounts_CycleCount::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CycleCounts_CycleCount::GetClassData() const {
  return &_class_data_;
}

void CycleCounts_CycleCount::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CycleCounts_CycleCount*>(&to_msg);
  auto& from = static_cast<const CycleCounts_CycleCount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CycleCounts.CycleCount)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_start() != 0) {
    _this->_internal_set_start(from._internal_start());
  }
  if (from._internal_end() != 0) {
    _this->_internal_set_end(from._internal_end());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CycleCounts_CycleCount::CopyFrom(const CycleCounts_CycleCount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CycleCounts.CycleCount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CycleCounts_CycleCount::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CycleCounts_CycleCount::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CycleCounts_CycleCount::InternalSwap(CycleCounts_CycleCount* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CycleCounts_CycleCount, _impl_.end_)
      + sizeof(CycleCounts_CycleCount::_impl_.end_)
      - PROTOBUF_FIELD_OFFSET(CycleCounts_CycleCount, _impl_.start_)>(
          reinterpret_cast<char*>(&_impl_.start_),
          reinterpret_cast<char*>(&other->_impl_.start_));
}

::google::protobuf::Metadata CycleCounts_CycleCount::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_binja_2eproto_getter, &descriptor_table_binja_2eproto_once,
      file_level_metadata_binja_2eproto[2]);
}
// ===================================================================

class CycleCounts::_Internal {
 public:
};

CycleCounts::CycleCounts(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CycleCounts)
}
inline PROTOBUF_NDEBUG_INLINE CycleCounts::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : cycle_counts_{visibility, arena, from.cycle_counts_},
        _cached_size_{0} {}

CycleCounts::CycleCounts(
    ::google::protobuf::Arena* arena,
    const CycleCounts& from)
    : ::google::protobuf::Message(arena) {
  CycleCounts* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:CycleCounts)
}
inline PROTOBUF_NDEBUG_INLINE CycleCounts::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : cycle_counts_{visibility, arena},
        _cached_size_{0} {}

inline void CycleCounts::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CycleCounts::~CycleCounts() {
  // @@protoc_insertion_point(destructor:CycleCounts)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CycleCounts::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CycleCounts::Clear() {
// @@protoc_insertion_point(message_clear_start:CycleCounts)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cycle_counts_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CycleCounts::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> CycleCounts::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CycleCounts_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .CycleCounts.CycleCount cycle_counts = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CycleCounts, _impl_.cycle_counts_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .CycleCounts.CycleCount cycle_counts = 1;
    {PROTOBUF_FIELD_OFFSET(CycleCounts, _impl_.cycle_counts_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CycleCounts_CycleCount>()},
  }}, {{
  }},
};

::uint8_t* CycleCounts::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CycleCounts)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .CycleCounts.CycleCount cycle_counts = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_cycle_counts_size()); i < n; i++) {
    const auto& repfield = this->_internal_cycle_counts().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CycleCounts)
  return target;
}

::size_t CycleCounts::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CycleCounts)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CycleCounts.CycleCount cycle_counts = 1;
  total_size += 1UL * this->_internal_cycle_counts_size();
  for (const auto& msg : this->_internal_cycle_counts()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CycleCounts::_class_data_ = {
    CycleCounts::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CycleCounts::GetClassData() const {
  return &_class_data_;
}

void CycleCounts::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CycleCounts*>(&to_msg);
  auto& from = static_cast<const CycleCounts&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CycleCounts)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_cycle_counts()->MergeFrom(
      from._internal_cycle_counts());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CycleCounts::CopyFrom(const CycleCounts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CycleCounts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CycleCounts::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CycleCounts::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CycleCounts::InternalSwap(CycleCounts* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.cycle_counts_.InternalSwap(&other->_impl_.cycle_counts_);
}

::google::protobuf::Metadata CycleCounts::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_binja_2eproto_getter, &descriptor_table_binja_2eproto_once,
      file_level_metadata_binja_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
