# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emulator.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'emulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mulator.proto\"@\n\nNextAction\x12\x1d\n\x10num_instructions\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x13\n\x11_num_instructions\"\xeb\x02\n\x0f\x45mulatorActions\x12\x32\n\x0cinstructions\x18\x01 \x03(\x0b\x32\x1c.EmulatorActions.Instruction\x1a=\n\x0cMemoryAccess\x12\r\n\x05vaddr\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x10\n\x08is_store\x18\x03 \x01(\x08\x1a#\n\nBranchFlow\x12\x15\n\ris_mispredict\x18\x01 \x01(\x08\x1a\xbf\x01\n\x0bInstruction\x12\x0e\n\x06opcode\x18\x01 \x01(\x0c\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\x04\x12\x39\n\rmemory_access\x18\x03 \x01(\x0b\x32\x1d.EmulatorActions.MemoryAccessH\x00\x88\x01\x01\x12\x35\n\x0b\x62ranch_flow\x18\x04 \x01(\x0b\x32\x1b.EmulatorActions.BranchFlowH\x01\x88\x01\x01\x42\x10\n\x0e_memory_accessB\x0e\n\x0c_branch_flow2B\n\x08\x45mulator\x12\x36\n\x15RecordEmulatorActions\x12\x10.EmulatorActions\x1a\x0b.NextActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEXTACTION']._serialized_start=18
  _globals['_NEXTACTION']._serialized_end=82
  _globals['_EMULATORACTIONS']._serialized_start=85
  _globals['_EMULATORACTIONS']._serialized_end=448
  _globals['_EMULATORACTIONS_MEMORYACCESS']._serialized_start=156
  _globals['_EMULATORACTIONS_MEMORYACCESS']._serialized_end=217
  _globals['_EMULATORACTIONS_BRANCHFLOW']._serialized_start=219
  _globals['_EMULATORACTIONS_BRANCHFLOW']._serialized_end=254
  _globals['_EMULATORACTIONS_INSTRUCTION']._serialized_start=257
  _globals['_EMULATORACTIONS_INSTRUCTION']._serialized_end=448
  _globals['_EMULATOR']._serialized_start=450
  _globals['_EMULATOR']._serialized_end=516
# @@protoc_insertion_point(module_scope)
