# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emulator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mulator.proto\"@\n\nNextAction\x12\x1d\n\x10num_instructions\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x13\n\x11_num_instructions\"\xea\x01\n\x0f\x45mulatorActions\x12\x32\n\x0cinstructions\x18\x01 \x03(\x0b\x32\x1c.EmulatorActions.Instruction\x1a=\n\x0cMemoryAccess\x12\r\n\x05vaddr\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x10\n\x08is_store\x18\x03 \x01(\x08\x1a\x64\n\x0bInstruction\x12\x0e\n\x06opcode\x18\x01 \x01(\x0c\x12\x36\n\nmem_access\x18\x02 \x01(\x0b\x32\x1d.EmulatorActions.MemoryAccessH\x00\x88\x01\x01\x42\r\n\x0b_mem_access2B\n\x08\x45mulator\x12\x36\n\x15RecordEmulatorActions\x12\x10.EmulatorActions\x1a\x0b.NextActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emulator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NEXTACTION']._serialized_start=18
  _globals['_NEXTACTION']._serialized_end=82
  _globals['_EMULATORACTIONS']._serialized_start=85
  _globals['_EMULATORACTIONS']._serialized_end=319
  _globals['_EMULATORACTIONS_MEMORYACCESS']._serialized_start=156
  _globals['_EMULATORACTIONS_MEMORYACCESS']._serialized_end=217
  _globals['_EMULATORACTIONS_INSTRUCTION']._serialized_start=219
  _globals['_EMULATORACTIONS_INSTRUCTION']._serialized_end=319
  _globals['_EMULATOR']._serialized_start=321
  _globals['_EMULATOR']._serialized_end=387
# @@protoc_insertion_point(module_scope)
